### ISSUE TITLE
Trivia error

### ISSUE THREAD

**Issue by Kezxo** [Twentysix26/Red-DiscordBot#21]
Got this error, seems I got the question right but it skipped to the next one instead of announcing the right answer or anything.

```
Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\discord\client.py", line 254, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "red.py", line 319, in on_message
    await trvsession.checkAnswer(message)
  File "red.py", line 490, in checkAnswer
    await client.send_message(self.channel, "You got it {}! **+1** to you!".format(message.author.name))
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\discord\client.py", line 947, in send_message
    yield from utils._verify_successful_response(resp)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\discord\utils.py", line 175, in _verify_successful_response
    data = yield from response.json()
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\aiohttp\client_reqrep.py", line 756, in json
    return loads(stripped.decode(encoding))
  File "C:\Program Files (x86)\Python35-32\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files (x86)\Python35-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files (x86)\Python35-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Twentysix26** [comment]
Seems like Discord's servers sent some weird data instead of JSON. Just a very rare issue
