### ISSUE TITLE
Issue when attempting to play music

### ISSUE THREAD

**Issue by tomearl98** [Twentysix26/Red-DiscordBot#43]
Hi, I'm seeing the following in the console when trying to use !youtube <video> or !play <playlist>:

Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/discord/client.py", line 259, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "red.py", line 290, in on_message
    await playVideo(message)
  File "red.py", line 1238, in playVideo
    currentPlaylist = Playlist(data)
  File "red.py", line 618, in __init__
    self.playSingleSong(self.playlist[0])
  File "red.py", line 682, in playSingleSong
    musicPlayer.start()
AttributeError: 'generator' object has no attribute 'start'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/discord/client.py", line 259, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "red.py", line 290, in on_message
    await playVideo(message)
  File "red.py", line 1234, in playVideo
    stopMusic()
  File "red.py", line 1370, in stopMusic
    musicPlayer.stop()
AttributeError: 'generator' object has no attribute 'stop'
^CTraceback (most recent call last):
  File "red.py", line 2048, in <module>
    loop.run_until_complete(main())
  File "/usr/local/lib/python3.5/asyncio/base_events.py", line 330, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.5/asyncio/base_events.py", line 301, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.5/asyncio/base_events.py", line 1162, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/local/lib/python3.5/selectors.py", line 432, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)

**Comment by Twentysix26** [comment]
Probably your ffmpeg installation is not working. Are you on Ubuntu/Debian? If so, you can find an autoinstall script in our server

**Comment by tomearl98** [comment]
I'm on CentOS 6.7, ffmpeg (and related binaries) are in $PATH

**Comment by mogokcp** [comment]
how do u installed on centos :(
