### ISSUE TITLE
Error removing badwords

### ISSUE THREAD

**Issue by seriosbrad** [Twentysix26/Red-DiscordBot#8]
Traceback (most recent call last):
  File "/usr/local/python351/lib/python3.5/site-packages/discord/client.py", line 251, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "red.py", line 263, in on_message
    await removeBadWords(message)
  File "red.py", line 1265, in removeBadWords
    dataIO.saveFilter(badwords)
AttributeError: module 'dataIO' has no attribute 'saveFilter'

**Comment by Twentysix26** [comment]
Fixed. Thanks for the report.
