### ISSUE TITLE
Error when trying to stream a local file

### ISSUE THREAD

**Issue by seriosbrad** [Twentysix26/Red-DiscordBot#9]
Ignoring exception in on_message
Traceback (most recent call last):
  File "red.py", line 445, in nextSong
    if isPlaylistValid([self.playlist[nextTrack]]): #Checks if it's a valid youtube link
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python351/lib/python3.5/site-packages/discord/client.py", line 251, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "red.py", line 198, in on_message
    await playLocal(message)
  File "red.py", line 944, in playLocal
    currentPlaylist = Playlist(data)
  File "red.py", line 437, in __init__
    self.nextSong(0)
  File "red.py", line 464, in nextSong
    logger.warning("Something went wrong with track " + self.playlist[self.current])
IndexError: list index out of range

CentOS 6 64bit

**Comment by Twentysix26** [comment]
Apparently a linux only problem. Need to look into it.

**Comment by Twentysix26** [comment]
Fix was easier than expected. The glob module was returning an empty list on Linux.

**Comment by mogokcp** [comment]
how do install on centos? :(
